services:
  - type: web
    name: lotto-ai-server
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:$PORT lotto_server:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
